language: objective-c

osx_image: xcode8
env:
  matrix:
    - DANGER=1
    - TEST="iOS"
    - TEST="OSX"
    - TEST="watchOS"
    - TEST="tvOS"
    - TEST="iOS-Example"

notifications:
  slack: rxswift:3ykt2Z61f8GkdvhCZTYPduOL
  email: false

script: 
  - if [ "${DANGER}" -eq 1 ]; then
       bundle exec danger --verbose;
    else
      xcodebuild -version;
      xcodebuild -showsdks;
      ./scripts/all-tests.sh "${TEST}";
    fi

